version: '3'

services:
  web:
      container_name: webadmin
      build:
        context: .
        dockerfile: ./dockerfile
      ports:
        - "3005:3000"
      depends_on:
        - api
      volumes:
        - ./public:/app/public
        - ./public/images:/app/public/images
        - ./public/pdfs:/app/public/pdfs
      networks:
        - theerasan-network
  api:
      container_name: api
      build:
        context: .
        dockerfile: ./dockerfile.api
      ports:
        - "3010:3010"
      depends_on:
        - db
      networks:
        - theerasan-network

  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - database_data:/var/lib/mysql
    networks:
        - theerasan-network


  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - theerasan-network

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
        - theerasan-network
volumes:
  database_data:
networks:
  theerasan-network:
    driver: bridge
